### ISSUE TITLE
Allow simple formatting in submission fields

### ISSUE THREAD

**Issue by ccoenen** [openeventstack/pretalx#105]
The description I wrote for a submission looks nice in the description field, I tried to add a list with simple dashes and newlines (screenshot, left half). The frontend, however, just renders it as one blob of text (screenshot, right half).

![grafik](https://user-images.githubusercontent.com/124909/29936137-6229de1a-8e81-11e7-9bbc-402015662fbb.png)

I would love this to at least honor manual breaks (`\r\n` or `\n` -> `<br>`) or perhaps even to parse basic markdown or html formatting. Markdown especially works quite well in my opinion.

**Comment by rixx** [comment]
Hmm, the frontend ought to honor markdown, but markdown lists require a newline ahead of them to work. Did you try that?

**Comment by ccoenen** [comment]
extra newline did the trick.
