### ISSUE TITLE
Decide how to deal with canceled talks

### ISSUE THREAD

**Issue by rixx** [openeventstack/pretalx#45]
We have a couple of choices here:

1) Don't list canceled talks in either old schedules or new ones (boo! for changing already-released schedules).
2) List canceled talks in both old and new schedules (in new ones only, if they still have a date. Need to update the scheduling site and the agenda queryset for this one).
2) Don't list canceled talks in new schedules, even if they still have a date, but keep them in old ones (need to expand the queryset in schedule generation for that, and maybe automatically remove the date from slots when a submission is being canceled).

While 1) is clearly a bad option, I'm not quite sure about the other two. I'm leaning towards 2) since it allows to publicly show what and where a canceled talk would have been (if the organizer desires to do so), which is nice for transparency and to avoid confusion.

@raphaelm, requesting your input.

**Comment by raphaelm** [comment]
I actually think (3) would be less confusing/more expected by the speaker and organizer.

**Comment by rixx** [comment]
(3) it is. Cancellation is also mentioned in the rss feed.
