### ISSUE TITLE
Slug for speaker profile links

### ISSUE THREAD

**Issue by rixx** [openeventstack/pretalx#47]
1. Use the username (current implementation, can't do that, it's a data leak).
2. Calculate a slug at registration time (if it doesn't change with name changes: it's a data leak. If it does change with name changes: produces dead links)
3. Don't provide a speaker profile page, just link other talks on talk pages (probably not as bad as it sounds?)

Input appreciated, @raphaelm.

**Comment by raphaelm** [comment]
I think either (2) with a *random* slug like for submissions or (3) are fine

**Comment by rixx** [comment]
I'm not even sure what would go on a speaker page except a short bio and links to conference talks, which is so little that it does not quite require a page of its own. OTOH speakers and folks in general might expect speaker pages. Hm.

**Comment by rixx** [comment]
We'll stick with (3) and provide a good speaker bio on talk pages.
