### ISSUE TITLE
schedule.xml has an invalid format

### ISSUE THREAD

**Issue by florolf** [openeventstack/pretalx#59]
I tried verifying the MRMCD 2017 `schedule.xml` (https://cfp.mrmcd.net/2017/schedule.xml) using https://c3voc.de/schedulexml/, which yielded a number of errors:

- The duration field has an odd format: `135.0:00` is not a valid time format, it must be of the form `(H)H:(M)M:(S)S`
- The slug is empty. This is apparently still being used in some corners of the c3voc publishing pipeline.

It would be great if those could be fixed for MRMCD. Thanks!

**Comment by rixx** [comment]
Erm, weird, I had tested against the c3voc validator earlier – must've broken during further development. Thanks for reporting it.

**Comment by rixx** [comment]
The issue appears to be fixed now. I introduced tests that run test schedules against the VOC `.xsd` schema, so this *should* be future safe and if not, tests are trivial to add and issues easy to verify.

Thanks for the report!
