### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by rixx** [openeventstack/pretalx#68]
Accounts should allow deletion – and if a relevant submission is connected, they should null all identifying fields instead, and set the user to be inactive.

**Comment by rixx** [comment]
… And since users who want their account to be deleted might not have access to it any longer, orga (or at least superusers) should have the possiblity to do so aswell.

**Comment by raphaelm** [comment]
Superusers sounds better, since accounts are not tightly coupled to events and just allowing any orga member of any event to do it is scary

**Comment by rixx** [comment]
On second thought I'm not really comfortable with giving any other user the chance to do this. I think this should remain with the speakers for now.

**Comment by raphaelm** [comment]
Super-users could/should totally be able to do so, but not orga, agreed

**Comment by rixx** [comment]
Yeah, but for now I'm okay with saying "superusers can call the `deactivate()` method on the user in the shell", and not providing a button for convenience. I'm willing to revisit the issue when it turns out relevant in the future. :)
