### ISSUE TITLE
following a team-invite link as a team member duplicates the entry

### ISSUE THREAD

**Issue by luto** [openeventstack/pretalx#92]
1. invite someone via mail on `/orga/event/foo/settings/team`
2. get and click the link inside the invite mail
3. on the invite page, login with the same account

The team entry is now duplicated. Removing one of the entries results in both of them getting deleted.
Instead one of the following should happen:
* display a positive message like "You were already part of this team. Good to have you with us!", delete the invitation.
* display a warning message like "You are already part of this team. Please log into a different account.", keep the invitation intact.

**Comment by rixx** [comment]
Closed in aca2267
